// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8poyFuWYb03L7vUGFIsUxo90CEkh79dU',
    appId: '1:869437902166:web:67cb78daf65d7008c05af7',
    messagingSenderId: '869437902166',
    projectId: 'flutterlab-firebase-7ed5e',
    authDomain: 'flutterlab-firebase-7ed5e.firebaseapp.com',
    storageBucket: 'flutterlab-firebase-7ed5e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzKkdF5Y_UPsh1pbDJBxDGaXp52de0G8s',
    appId: '1:869437902166:android:5be9481339f20de8c05af7',
    messagingSenderId: '869437902166',
    projectId: 'flutterlab-firebase-7ed5e',
    storageBucket: 'flutterlab-firebase-7ed5e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdO52nntiyXlt2Cy0GUzZAd9ikkJa5hZ8',
    appId: '1:869437902166:ios:11bc0a306726f254c05af7',
    messagingSenderId: '869437902166',
    projectId: 'flutterlab-firebase-7ed5e',
    storageBucket: 'flutterlab-firebase-7ed5e.appspot.com',
    iosClientId: '869437902166-cc64s142cclbhc2s0n20259qbv03r4sj.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterLabFirebas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdO52nntiyXlt2Cy0GUzZAd9ikkJa5hZ8',
    appId: '1:869437902166:ios:11bc0a306726f254c05af7',
    messagingSenderId: '869437902166',
    projectId: 'flutterlab-firebase-7ed5e',
    storageBucket: 'flutterlab-firebase-7ed5e.appspot.com',
    iosClientId: '869437902166-cc64s142cclbhc2s0n20259qbv03r4sj.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterLabFirebas',
  );
}
